apiVersion: v1
kind: Pod
metadata:
  name: multi-contianer-pod
  namespace: expense
  labels:
    environment: dev
spec:
  containers:
  - name: expense
    image: nginx
  - name: alma
    image: almalinux:8
    command: ["sleep", "20"]