apiVersion: v1
kind: Pod
metadata:
  name: expense
  namespace: expense
  labels:
    environment: dev
spec:
  containers:
  - name: expense
    image: nginx
  - name: alma
    image: almalinux:9
    command: "sleep 20"