apiVersion: v1
kind: Pod
metadata:
  name: annotation-pod
  namespace: expense
  labels:
    environment: dev
  annotations:
    kubernetes.io/created-by: 'shashi'
    jenkins.build.url: 'https://jenkins.com/build/123'
spec:
  containers:
  - name: expense-container
    image: nginx