apiVersion: v1
kind: Pod
metadata:
  name: env-test
  namespace: expense
spec:
  containers:
  - name: expense-container
    image: nginx
    env:
    - name: environement
      value: qa
    - brand: macys
      value: mcom