apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
  namespace: expense    
spec:
  containers:   
  - name: expense-container
    image: nginx
    envFrom:
    - secretRef:
        name: expense-secret