apiVersion: v1
kind : PersistentVolume
metadata:
  name: ebs-pv    
spec:
  accessModes:
    - ReadWriteOnce
  capacity:   
    storage: 5Gi 
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0e1f2d3c4b5a6d7e8 # Replace with your EBS volume ID 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc 
spec:
  storageClassName: "" # Use the default storage class
  valumeName: ebs-pv
  accessModes:
    - ReadWriteOnce     
  resources:
    requests:
      storage: 5Gi    
      
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-pod   
spec:
  containers:
    - name: ebs-container
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: ebs-volume
  volumes:
    - name: ebs-volume
      persistentVolumeClaim:
        claimName: ebs-pvc