
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  storageClassName: "expense-ebs" # Use the default storage class
  valumeName: ebs-dynamic
  accessModes:
    - ReadWriteOnce     
  resources:
    requests:
      storage: 4Gi 
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-dynamic
  labels:
    app: ebs-app  
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: ebs-volume
  volumes:
    - name: ebs-volume
      persistentVolumeClaim:
        claimName: ebs-dynamic
