
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  storageClassName: "expense-ebs" # Use the default storage class
  valumeName: ebs-dynamic
  accessModes:
    - ReadWriteOnce     
  resources:
    requests:
      storage: 4Gi 